"""add token usage columns to assistant_drafts

Revision ID: c5fd03dcfa20
Revises: 38c21f1707ed
Create Date: 2026-08-07 16:56:12.415720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fd03dcfa20'
down_revision: Union[str, Sequence[str], None] = '38c21f1707ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_drafts', sa.Column('tokens_input', sa.Integer(), nullable=True))
    op.add_column('assistant_drafts', sa.Column('tokens_output', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_drafts', 'tokens_output')
    op.drop_column('assistant_drafts', 'tokens_input')
    # ### end Alembic commands ###
